# Site settings
title: nityadhyaana
email: swathi.ammalu007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We teach yoga and calm your mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: swathi.ammalu007@gmail.com
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
